### ISSUE TITLE
code > general > carousels

### ISSUE THREAD

**Issue by tiredandwired** [UMNLibraries/design-system#4]
While I appreciate this (so, so much), is it fair to create a category for the sole purpose of saying no, or might that be better presented as needed?

**Comment by puzumaki** [comment]
This may be too flippant without a more thorough explanation. I would prefer to have the decision documented. While the current text is straight to the point, would it be friendlier to include all the reasons for it?

**Comment by puzumaki** [comment]
Added more content to be more easily available. Can add more if it's necessary for people to understand how carousels are a poor UX choice.
