### ISSUE TITLE
code > links

### ISSUE THREAD

**Issue by tiredandwired** [UMNLibraries/design-system#6]
External link
    will there be a button/checkbox for this in Drupal?

Link list
    maybe some context around when or why you would use the standalone link?

**Comment by puzumaki** [comment]
We need to have a conversation with Gabe, this may be two different items for "onsite link" vs. "external link". I'm not sure how Drupal will implement this.

**Comment by puzumaki** [comment]
I could guess as to the use of the standalone link, but it's hard to discern without content. I would be fine with putting something there though.

**Comment by puzumaki** [comment]
Since we rolled back external link identification, and I added a little bit about context for the described links, I believe this has been addressed.
