### ISSUE TITLE
code > images

### ISSUE THREAD

**Issue by tiredandwired** [UMNLibraries/design-system#8]
Manual image optimization
    not everyone has Photoshop (and i think actually most don’t).. there needs to be a fallback method here, even if that means "contact webdev/communications/whatever"

Manual SVG optimization
    same as above re: Illustrator

Available icons
do we need some note about whether or not folks can make up their own icons? (i'm guessing they shouldn't?)

**Comment by puzumaki** [comment]
The idea here is Drupal will manage most of it (automated, vs. manual), these instructions are here for anything that won't be processed by Drupal. Gabe is still working through this, but seems worth clarifying the automated options here once we have a better idea how that plays out.

**Comment by puzumaki** [comment]
I've added a line for the case where people want to use an icon not listed. Thanks!

**Comment by puzumaki** [comment]
I think this was addressed?
